import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "REST-API2",
  description: "Generated by Orazbek",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} mx-auto my-0 min-h-dvh max-w-screen-xl`}
    >
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
